---
temp_space: "{{ ansible_env.TEMP }}\\BlackMegaTemp"

sysinternal_tools:
  - procexp
  - procmon
  - AutoRuns

choco_packages:
  - vcredist140
  - netfx-4.8
  - openjdk17
  - python
  - git
  - winrar
  - 7zip
  - wireshark
  - networkmonitor
  - putty
  - die
  - explorersuite
  - pebear
  - PeStudio
  - reshack
  - regshot
  - dnspy
  - dnspy-netfx
  - x64dbg.portable
  - ghidra
  - javadecompiler-gui
  - VisualStudioCode
  - HxD
  - hashmyfiles
  - dbeaver
  - notepadplusplus
  - sumatrapdf
  - spystudio
